# Generated by Django 5.2.9 on 2025-12-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('github_link', models.URLField()),
                ('live_link', models.URLField(blank=True)),
                ('category', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='projects/')),
                ('created_at', models.DateField()),
                ('tech_stack', models.ManyToManyField(to='projects.technology')),
            ],
        ),
    ]
